description	"VPN failover daemon"

start on (filesystem or runlevel [2345]) and stopped nat
stop on runlevel [!2345]

respawn
respawn limit 10 5
umask 077

console log

exec /usr/bin/python ${BASE}/vpn-failover/daemon.py

